port: 3000

db:
  type: postgres
  url: postgres://u4dtoqj0aq9e0c:p09513c32a4ea2e1ece3141d19625c68256b1d7851f90b0269573cc3180d26f03@c3gtj1dt5vh48j.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d42biknv9hcbhf?sslmode=require
  ssl: true
  sslOptions:
    auto: true
  schema: public

ssl:
  enabled: false
  port: 3443
  provider: custom
  format: pem
  key: path/to/key.pem
  cert: path/to/cert.pem
  pfx: path/to/cert.pfx
  passphrase: null
  dhparam: null
  domain: wiki.yourdomain.com
  subscriberEmail: admin@example.com

pool:
  # min: 2
  # max: 10

bindIP: 0.0.0.0
logLevel: info
logFormat: default
offline: false
ha: false
dataPath: ./data
bodyParserLimit: 5mb
